# Generated by Django 3.0.4 on 2020-03-23 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('IP', models.GenericIPAddressField()),
                ('port', models.IntegerField()),
            ],
        ),
    ]
