# Generated by Django 3.0.4 on 2020-03-24 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0002_auto_20200324_1436'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiver_id', models.IntegerField()),
                ('amount', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='node',
            name='PORT',
            field=models.IntegerField(default=5000),
        ),
        migrations.AlterField(
            model_name='node',
            name='status',
            field=models.TextField(default='Offline', max_length=7),
        ),
    ]
