# Generated by Django 3.0.4 on 2020-03-24 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0004_auto_20200324_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='id',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
