# Generated by Django 3.0.4 on 2020-03-24 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0006_auto_20200324_1939'),
    ]

    operations = [
        migrations.RenameField(
            model_name='node',
            old_name='node_id',
            new_name='node_index',
        ),
    ]
